// The client half of the Phase B progression parity gate (spec B.1.0).
//
// The star/Mission numbers a teacher acts on are produced twice — once here in
// Dart for the learner, once server-side in `admin-dash-api` for the teacher
// dashboard. A silent divergence between them is worse than an outage, so the
// two implementations are pinned to ONE set of test vectors.
//
// Those vectors are VENDORED, not shared: each repo owns a full, byte-identical
// copy, and there is no cross-repo import, submodule, or runtime fetch at test
// time. The checksum is the entire coupling mechanism:
//
//   * this test recomputes the sha256 of every vector file in THIS repo's
//     `test/fixtures/parity/progression/` and asserts it matches THIS repo's
//     committed `MANIFEST.sha256`, so a one-byte drift here turns THIS repo's CI
//     red — whether from corruption, a partial edit, or a fixture change landed
//     without regenerating the manifest;
//   * because both repos are expected to carry identical manifest CONTENT, a
//     vector changed on only one side leaves the two committed manifests
//     disagreeing, which is visible in review.
//
// The Python half is `admin-dash-api/tests/test_progression_parity_fixtures.py`;
// the manifest is generated by `admin-dash-api/tests/fixtures/parity/
// gen_progression_manifest.py` and copied here alongside the vectors it
// describes.
//
// Falsification: edit one byte of one fixture without regenerating the manifest
// and this test must fail.
//
// ---------------------------------------------------------------------------
// Why sha256 is implemented here rather than imported
// ---------------------------------------------------------------------------
// `package:crypto` is only a TRANSITIVE dependency of this app, and importing it
// would both trip `depend_on_referenced_packages` (flutter_lints) and create a
// hidden dependency. Adding it to `pubspec.yaml` is not an option this change can
// take. So the digest is computed inline, in ~60 lines of FIPS 180-4 SHA-256.
//
// This is a fixture-integrity checksum, not a security primitive, and its
// correctness is externally pinned rather than assumed: it must reproduce, byte
// for byte, a manifest that Python's `hashlib.sha256` and the system
// `shasum -a 256` independently produce. A wrong implementation cannot pass.

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:path/path.dart' as p;

const List<int> _k = <int>[
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, //
  0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
  0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
  0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
  0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc,
  0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
  0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
  0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
  0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
  0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3,
  0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5,
  0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
  0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
  0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
];

int _rotr(int x, int n) => ((x >> n) | (x << (32 - n))) & 0xffffffff;

/// FIPS 180-4 SHA-256 over [message], returned as lowercase hex.
String sha256Hex(List<int> message) {
  final h = <int>[
    0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, //
    0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
  ];

  // Pad: 0x80, then zeroes, then the 64-bit big-endian bit length.
  final padded = <int>[...message, 0x80];
  while (padded.length % 64 != 56) {
    padded.add(0);
  }
  final bitLength = message.length * 8;
  final lengthBytes = ByteData(8)..setUint64(0, bitLength);
  padded.addAll(lengthBytes.buffer.asUint8List());

  final w = Int32List(64);
  for (var chunk = 0; chunk < padded.length; chunk += 64) {
    for (var i = 0; i < 16; i++) {
      final j = chunk + i * 4;
      w[i] =
          (padded[j] << 24) |
          (padded[j + 1] << 16) |
          (padded[j + 2] << 8) |
          padded[j + 3];
    }
    for (var i = 16; i < 64; i++) {
      final s0 =
          _rotr(w[i - 15] & 0xffffffff, 7) ^
          _rotr(w[i - 15] & 0xffffffff, 18) ^
          ((w[i - 15] & 0xffffffff) >> 3);
      final s1 =
          _rotr(w[i - 2] & 0xffffffff, 17) ^
          _rotr(w[i - 2] & 0xffffffff, 19) ^
          ((w[i - 2] & 0xffffffff) >> 10);
      w[i] = (w[i - 16] + s0 + w[i - 7] + s1) & 0xffffffff;
    }

    var a = h[0], b = h[1], c = h[2], d = h[3];
    var e = h[4], f = h[5], g = h[6], hh = h[7];

    for (var i = 0; i < 64; i++) {
      final s1 = _rotr(e, 6) ^ _rotr(e, 11) ^ _rotr(e, 25);
      final ch = (e & f) ^ ((~e & 0xffffffff) & g);
      final temp1 = (hh + s1 + ch + _k[i] + (w[i] & 0xffffffff)) & 0xffffffff;
      final s0 = _rotr(a, 2) ^ _rotr(a, 13) ^ _rotr(a, 22);
      final maj = (a & b) ^ (a & c) ^ (b & c);
      final temp2 = (s0 + maj) & 0xffffffff;

      hh = g;
      g = f;
      f = e;
      e = (d + temp1) & 0xffffffff;
      d = c;
      c = b;
      b = a;
      a = (temp1 + temp2) & 0xffffffff;
    }

    h[0] = (h[0] + a) & 0xffffffff;
    h[1] = (h[1] + b) & 0xffffffff;
    h[2] = (h[2] + c) & 0xffffffff;
    h[3] = (h[3] + d) & 0xffffffff;
    h[4] = (h[4] + e) & 0xffffffff;
    h[5] = (h[5] + f) & 0xffffffff;
    h[6] = (h[6] + g) & 0xffffffff;
    h[7] = (h[7] + hh) & 0xffffffff;
  }

  return h.map((v) => v.toRadixString(16).padLeft(8, '0')).join();
}

/// Parse `<hex digest>  <filename>` lines into `{filename: digest}`.
///
/// A malformed line THROWS: a manifest we cannot parse must fail the check, never
/// silently verify nothing.
Map<String, String> parseManifest(String text) {
  final entries = <String, String>{};
  for (final raw in const LineSplitter().convert(text)) {
    final line = raw.trim();
    if (line.isEmpty) continue;
    final separator = line.indexOf('  ');
    if (separator <= 0 || separator + 2 >= line.length) {
      throw FormatException('malformed manifest line: $raw');
    }
    entries[line.substring(separator + 2)] = line.substring(0, separator);
  }
  return entries;
}

void main() {
  final progressionDir = Directory(
    p.join('test', 'fixtures', 'parity', 'progression'),
  );
  final manifestFile = File(p.join(progressionDir.path, 'MANIFEST.sha256'));

  const regenerate =
      'Regenerate it in admin-dash-api, then copy progression/ byte-identically '
      'back into client/test/fixtures/parity/:\n'
      '  python tests/fixtures/parity/gen_progression_manifest.py';

  List<File> vectorFiles() =>
      progressionDir
          .listSync()
          .whereType<File>()
          .where((f) => p.extension(f.path) == '.json')
          .toList()
        ..sort((a, b) => p.basename(a.path).compareTo(p.basename(b.path)));

  group('progression parity fixtures', () {
    test('the sha256 implementation matches known FIPS 180-4 vectors', () {
      // Guards the guard: if this drifts, every assertion below is meaningless.
      expect(
        sha256Hex(utf8.encode('')),
        'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      );
      expect(
        sha256Hex(utf8.encode('abc')),
        'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad',
      );
      expect(
        sha256Hex(
          utf8.encode(
            'abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq',
          ),
        ),
        '248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1',
      );
    });

    test('the manifest exists and is parseable', () {
      expect(
        manifestFile.existsSync(),
        isTrue,
        reason: 'missing ${manifestFile.path}\n$regenerate',
      );
      expect(
        parseManifest(manifestFile.readAsStringSync()),
        isNotEmpty,
        reason: '${manifestFile.path} lists no vector files\n$regenerate',
      );
    });

    test('the manifest covers exactly the vector files present', () {
      final listed = parseManifest(
        manifestFile.readAsStringSync(),
      ).keys.toSet();
      final onDisk = vectorFiles().map((f) => p.basename(f.path)).toSet();

      expect(
        onDisk,
        equals(listed),
        reason:
            'progression/ and MANIFEST.sha256 disagree on which vectors '
            'exist\n$regenerate',
      );
    });

    test('every vector file matches its committed digest', () {
      final manifest = parseManifest(manifestFile.readAsStringSync());

      for (final file in vectorFiles()) {
        final name = p.basename(file.path);
        expect(
          sha256Hex(file.readAsBytesSync()),
          manifest[name],
          reason: '$name does not match its committed sha256\n$regenerate',
        );
      }
    });

    test('the vectors are readable and carry the expected vector families', () {
      // Byte-identity is worthless if the bytes are not the fixture we think.
      final rollup =
          jsonDecode(
                File(
                  p.join(progressionDir.path, 'rollup_vectors.json'),
                ).readAsStringSync(),
              )
              as Map<String, dynamic>;
      final starCount =
          jsonDecode(
                File(
                  p.join(progressionDir.path, 'star_count_vectors.json'),
                ).readAsStringSync(),
              )
              as Map<String, dynamic>;

      expect(rollup['vectors'], isNotEmpty);
      expect(starCount['vectors'], isNotEmpty);
      expect(rollup['float_tolerance'], 1e-9);
      // The resolver constants the Python port claims to mirror are the ones
      // this client actually declares (lo_progression.dart /
      // quest_progression_resolver.dart).
      expect(rollup['default_stars_to_unlock_objective'], 10);
      expect(rollup['band_falloff_missions'], 3);
      expect(rollup['band_ceiling'], 2.0);
    });
  });
}
