import 'package:fluffychat/pangea/morphs/morph_meaning/morph_info_response.dart';

/// English defaults for the localizations endpoint (`/morph_meaning`).
///
/// Used as a fallback when the choreographer is unreachable so the grammar
/// page still has copy. Mirrors the feature/tag set in [defaultMorphMapping]
/// so every code the canonical fallback can surface has a matching title +
/// description here.
final MorphInfoResponse defaultMorphInfoResponse = MorphInfoResponse.fromJson({
  "user_l1": "en",
  "user_l2": "en",
  "features": [
    {
      "code": "pos",
      "l1_title": "Part of speech",
      "tags": [
        {"code": "ADJ", "l1_title": "Adjective", "l1_description": "A word that describes a noun, like 'happy' or 'blue'."},
        {"code": "ADP", "l1_title": "Adposition", "l1_description": "A preposition or postposition, like 'in', 'on', or 'under'."},
        {"code": "ADV", "l1_title": "Adverb", "l1_description": "A word that modifies a verb, adjective, or other adverb, like 'quickly' or 'very'."},
        {"code": "AFFIX", "l1_title": "Affix", "l1_description": "A piece added to a word to change its meaning, like a prefix or suffix."},
        {"code": "AUX", "l1_title": "Auxiliary", "l1_description": "A helping verb used with a main verb, like 'is', 'have', or 'will'."},
        {"code": "CCONJ", "l1_title": "Coordinating conjunction", "l1_description": "A word that joins equal parts of a sentence, like 'and', 'but', or 'or'."},
        {"code": "COMPN", "l1_title": "Compound noun", "l1_description": "A noun made of two or more words working as one, like 'toothbrush'."},
        {"code": "DET", "l1_title": "Determiner", "l1_description": "A word that introduces a noun, like 'the', 'a', 'this', or 'some'."},
        {"code": "IDIOM", "l1_title": "Idiom", "l1_description": "A fixed phrase with a meaning different from its literal words, like 'kick the bucket'."},
        {"code": "INTJ", "l1_title": "Interjection", "l1_description": "A short word expressing emotion, like 'oh', 'wow', or 'ouch'."},
        {"code": "NOUN", "l1_title": "Noun", "l1_description": "A word for a person, place, thing, or idea, like 'book' or 'happiness'."},
        {"code": "NUM", "l1_title": "Numeral", "l1_description": "A number word, like 'three' or 'first'."},
        {"code": "PART", "l1_title": "Particle", "l1_description": "A small function word that adds grammatical meaning, like 'to' in 'to go'."},
        {"code": "PHRASALV", "l1_title": "Phrasal verb", "l1_description": "A verb combined with a particle that changes its meaning, like 'give up'."},
        {"code": "PRON", "l1_title": "Pronoun", "l1_description": "A word that stands in for a noun, like 'he', 'she', 'it', or 'they'."},
        {"code": "PUNCT", "l1_title": "Punctuation", "l1_description": "Marks like commas, periods, and question marks that structure writing."},
        {"code": "SCONJ", "l1_title": "Subordinating conjunction", "l1_description": "A word that joins a dependent clause to a main one, like 'because' or 'although'."},
        {"code": "SPACE", "l1_title": "Space", "l1_description": "Whitespace between words or tokens."},
        {"code": "SYM", "l1_title": "Symbol", "l1_description": "A non-letter symbol used in text, like '\$' or '%'."},
        {"code": "VERB", "l1_title": "Verb", "l1_description": "A word for an action or state, like 'run', 'is', or 'become'."},
        {"code": "X", "l1_title": "Other", "l1_description": "A word that doesn't fit a standard part of speech."},
      ],
    },
    {
      "code": "advtype",
      "l1_title": "Adverb type",
      "tags": [
        {"code": "Adverbial", "l1_title": "Adverbial", "l1_description": "An adverbial word or phrase modifying a verb or sentence."},
        {"code": "Tim", "l1_title": "Time", "l1_description": "An adverb of time, like 'yesterday' or 'soon'."},
      ],
    },
    {
      "code": "aspect",
      "l1_title": "Aspect",
      "tags": [
        {"code": "Imp", "l1_title": "Imperfective", "l1_description": "An ongoing or incomplete action, like 'was walking'."},
        {"code": "Perf", "l1_title": "Perfective", "l1_description": "A completed action viewed as a whole, like 'walked'."},
        {"code": "Prog", "l1_title": "Progressive", "l1_description": "An action in progress, like 'is walking'."},
        {"code": "Hab", "l1_title": "Habitual", "l1_description": "A repeated or customary action, like 'used to walk'."},
      ],
    },
    {
      "code": "case",
      "l1_title": "Case",
      "tags": [
        {"code": "Nom", "l1_title": "Nominative", "l1_description": "The case of the subject of a sentence."},
        {"code": "Acc", "l1_title": "Accusative", "l1_description": "The case of the direct object."},
        {"code": "Dat", "l1_title": "Dative", "l1_description": "The case of the indirect object, often 'to' or 'for' someone."},
        {"code": "Gen", "l1_title": "Genitive", "l1_description": "The case showing possession or relation, like 'of' or 's."},
        {"code": "Voc", "l1_title": "Vocative", "l1_description": "The case used to address someone directly."},
        {"code": "Abl", "l1_title": "Ablative", "l1_description": "The case marking movement away from or source."},
        {"code": "Loc", "l1_title": "Locative", "l1_description": "The case marking location, like 'in' or 'at' a place."},
        {"code": "All", "l1_title": "Allative", "l1_description": "The case marking movement toward a place."},
        {"code": "Ins", "l1_title": "Instrumental", "l1_description": "The case marking the means or instrument of an action."},
        {"code": "Ess", "l1_title": "Essive", "l1_description": "The case marking a temporary state, like 'as a teacher'."},
        {"code": "Tra", "l1_title": "Translative", "l1_description": "The case marking change of state, like 'into' a teacher."},
        {"code": "Com", "l1_title": "Comitative", "l1_description": "The case marking accompaniment, like 'with' someone."},
        {"code": "Par", "l1_title": "Partitive", "l1_description": "The case marking a part of a whole."},
        {"code": "Adv", "l1_title": "Adverbial", "l1_description": "A case used to form adverbial expressions."},
        {"code": "Ref", "l1_title": "Referential", "l1_description": "A case used to refer to or about something."},
        {"code": "Rel", "l1_title": "Relative", "l1_description": "A case marking a relationship between elements."},
        {"code": "Equ", "l1_title": "Equative", "l1_description": "The case marking equality or comparison, like 'as big as'."},
        {"code": "Dis", "l1_title": "Distributive", "l1_description": "The case marking distribution, like 'one per person'."},
        {"code": "Abs", "l1_title": "Absolutive", "l1_description": "In ergative languages, the case of subjects of intransitive verbs and objects of transitive ones."},
        {"code": "Erg", "l1_title": "Ergative", "l1_description": "In ergative languages, the case of the subject of a transitive verb."},
        {"code": "Cau", "l1_title": "Causal", "l1_description": "The case marking cause or reason, like 'because of'."},
        {"code": "Ben", "l1_title": "Benefactive", "l1_description": "The case marking the beneficiary of an action, like 'for someone'."},
        {"code": "Sub", "l1_title": "Sublative", "l1_description": "The case marking movement onto or under a surface."},
        {"code": "Sup", "l1_title": "Superessive", "l1_description": "The case marking position on top of something."},
        {"code": "Tem", "l1_title": "Temporal", "l1_description": "The case marking a time, like 'on Monday'."},
        {"code": "Obl", "l1_title": "Oblique", "l1_description": "A general non-subject form of a noun or pronoun."},
        {"code": "Acc,Dat", "l1_title": "Accusative/Dative", "l1_description": "A form that serves as both accusative and dative."},
        {"code": "Acc,Nom", "l1_title": "Accusative/Nominative", "l1_description": "A form that serves as both accusative and nominative."},
        {"code": "Pre", "l1_title": "Prepositional", "l1_description": "A case used after prepositions, common in some Slavic languages."},
      ],
    },
    {
      "code": "conjtype",
      "l1_title": "Conjunction type",
      "tags": [
        {"code": "Coord", "l1_title": "Coordinating", "l1_description": "Joins equal parts of a sentence, like 'and' or 'but'."},
        {"code": "Sub", "l1_title": "Subordinating", "l1_description": "Connects a dependent clause to a main clause, like 'because'."},
        {"code": "Cmp", "l1_title": "Comparative", "l1_description": "Used in comparisons, like 'than' or 'as'."},
      ],
    },
    {
      "code": "definite",
      "l1_title": "Definiteness",
      "tags": [
        {"code": "Def", "l1_title": "Definite", "l1_description": "Refers to a specific known thing, like 'the' in English."},
        {"code": "Ind", "l1_title": "Indefinite", "l1_description": "Refers to a non-specific thing, like 'a' in English."},
        {"code": "Cons", "l1_title": "Construct state", "l1_description": "A noun form used in possessive constructions, common in Semitic languages."},
      ],
    },
    {
      "code": "degree",
      "l1_title": "Degree",
      "tags": [
        {"code": "Pos", "l1_title": "Positive", "l1_description": "The base form of an adjective or adverb, like 'big'."},
        {"code": "Cmp", "l1_title": "Comparative", "l1_description": "The comparing form, like 'bigger' or 'more big'."},
        {"code": "Sup", "l1_title": "Superlative", "l1_description": "The highest-degree form, like 'biggest' or 'most big'."},
        {"code": "Abs", "l1_title": "Absolute superlative", "l1_description": "A very high degree without direct comparison, like 'very big'."},
      ],
    },
    {
      "code": "evident",
      "l1_title": "Evidentiality",
      "tags": [
        {"code": "Fh", "l1_title": "Firsthand", "l1_description": "Information the speaker directly experienced."},
        {"code": "Nfh", "l1_title": "Non-firsthand", "l1_description": "Information learned indirectly, like hearsay or inference."},
      ],
    },
    {
      "code": "foreign",
      "l1_title": "Foreign",
      "tags": [
        {"code": "Yes", "l1_title": "Foreign word", "l1_description": "A word borrowed from another language."},
      ],
    },
    {
      "code": "gender",
      "l1_title": "Gender",
      "tags": [
        {"code": "Masc", "l1_title": "Masculine", "l1_description": "Grammatically masculine, like 'he' or 'el chico'."},
        {"code": "Fem", "l1_title": "Feminine", "l1_description": "Grammatically feminine, like 'she' or 'la chica'."},
        {"code": "Neut", "l1_title": "Neuter", "l1_description": "Grammatically neither masculine nor feminine, like 'it' or German 'das'."},
        {"code": "Com", "l1_title": "Common", "l1_description": "A combined non-neuter gender used in some languages."},
      ],
    },
    {
      "code": "mood",
      "l1_title": "Mood",
      "tags": [
        {"code": "Ind", "l1_title": "Indicative", "l1_description": "States a fact, like 'she runs'."},
        {"code": "Imp", "l1_title": "Imperative", "l1_description": "Gives a command, like 'run!'"},
        {"code": "Sub", "l1_title": "Subjunctive", "l1_description": "Expresses wishes, doubts, or hypotheticals, like 'if I were'."},
        {"code": "Cnd", "l1_title": "Conditional", "l1_description": "Expresses what would happen, like 'I would run'."},
        {"code": "Opt", "l1_title": "Optative", "l1_description": "Expresses a wish, like 'may you live long'."},
        {"code": "Jus", "l1_title": "Jussive", "l1_description": "A third-person command, like 'let them go'."},
        {"code": "Adm", "l1_title": "Admirative", "l1_description": "Expresses surprise about new information."},
        {"code": "Des", "l1_title": "Desiderative", "l1_description": "Expresses desire to do something, like 'wants to run'."},
        {"code": "Nec", "l1_title": "Necessitative", "l1_description": "Expresses necessity, like 'must run'."},
        {"code": "Pot", "l1_title": "Potential", "l1_description": "Expresses possibility, like 'might run'."},
        {"code": "Prp", "l1_title": "Purposive", "l1_description": "Expresses purpose, like 'in order to run'."},
        {"code": "Qot", "l1_title": "Quotative", "l1_description": "Marks reported speech, like 'they said'."},
        {"code": "Int", "l1_title": "Interrogative", "l1_description": "Forms a question, like 'do you run?'"},
      ],
    },
    {
      "code": "nountype",
      "l1_title": "Noun type",
      "tags": [
        {"code": "Prop", "l1_title": "Proper noun", "l1_description": "A name of a specific person, place, or thing, like 'Paris'."},
        {"code": "Comm", "l1_title": "Common noun", "l1_description": "A general noun, like 'city' or 'book'."},
        {"code": "Not_proper", "l1_title": "Not proper", "l1_description": "A noun that is not a proper name."},
      ],
    },
    {
      "code": "numform",
      "l1_title": "Number form",
      "tags": [
        {"code": "Digit", "l1_title": "Digit", "l1_description": "A number written with digits, like '7'."},
        {"code": "Word", "l1_title": "Word", "l1_description": "A number written as a word, like 'seven'."},
        {"code": "Roman", "l1_title": "Roman numeral", "l1_description": "A number written with Roman numerals, like 'VII'."},
        {"code": "Letter", "l1_title": "Letter", "l1_description": "A number written using letters, like Hebrew alphabet numerals."},
      ],
    },
    {
      "code": "numtype",
      "l1_title": "Number type",
      "tags": [
        {"code": "Card", "l1_title": "Cardinal", "l1_description": "A counting number, like 'one' or 'three'."},
        {"code": "Ord", "l1_title": "Ordinal", "l1_description": "A ranking number, like 'first' or 'third'."},
        {"code": "Mult", "l1_title": "Multiplicative", "l1_description": "Expresses how many times, like 'twice' or 'triple'."},
        {"code": "Frac", "l1_title": "Fractional", "l1_description": "A fraction, like 'half' or 'quarter'."},
        {"code": "Sets", "l1_title": "Sets", "l1_description": "A number describing sets, like 'pair' or 'dozen'."},
        {"code": "Range", "l1_title": "Range", "l1_description": "A range of numbers, like 'two to five'."},
        {"code": "Dist", "l1_title": "Distributive", "l1_description": "Distributes a number, like 'one each'."},
      ],
    },
    {
      "code": "number",
      "l1_title": "Number",
      "tags": [
        {"code": "Sing", "l1_title": "Singular", "l1_description": "Refers to one, like 'cat'."},
        {"code": "Plur", "l1_title": "Plural", "l1_description": "Refers to more than one, like 'cats'."},
        {"code": "Dual", "l1_title": "Dual", "l1_description": "Refers to exactly two, used in some languages."},
        {"code": "Tri", "l1_title": "Trial", "l1_description": "Refers to exactly three, found in a few languages."},
        {"code": "Pauc", "l1_title": "Paucal", "l1_description": "Refers to a few, distinct from singular and plural."},
        {"code": "Grpa", "l1_title": "Greater paucal", "l1_description": "Refers to a larger few, between paucal and plural."},
        {"code": "Grpl", "l1_title": "Greater plural", "l1_description": "Refers to an especially large group."},
        {"code": "Inv", "l1_title": "Inverse number", "l1_description": "Marks the less expected number for a noun class."},
      ],
    },
    {
      "code": "number[psor]",
      "l1_title": "Possessor number",
      "tags": [
        {"code": "Sing", "l1_title": "Singular possessor", "l1_description": "The owner is one person or thing, like 'my' or 'his'."},
        {"code": "Plur", "l1_title": "Plural possessor", "l1_description": "The owners are more than one, like 'our' or 'their'."},
        {"code": "Dual", "l1_title": "Dual possessor", "l1_description": "Exactly two owners, used in some languages."},
      ],
    },
    {
      "code": "person",
      "l1_title": "Person",
      "tags": [
        {"code": "0", "l1_title": "Zero person", "l1_description": "An impersonal or generic subject, like 'one says'."},
        {"code": "1", "l1_title": "First person", "l1_description": "Refers to the speaker, like 'I' or 'we'."},
        {"code": "2", "l1_title": "Second person", "l1_description": "Refers to the listener, like 'you'."},
        {"code": "3", "l1_title": "Third person", "l1_description": "Refers to someone or something else, like 'he', 'she', or 'they'."},
        {"code": "4", "l1_title": "Fourth person", "l1_description": "A separate third-person referent used in some languages."},
      ],
    },
    {
      "code": "polarity",
      "l1_title": "Polarity",
      "tags": [
        {"code": "Pos", "l1_title": "Positive", "l1_description": "An affirmative form, like 'is' or 'do'."},
        {"code": "Neg", "l1_title": "Negative", "l1_description": "A negated form, like 'isn't' or 'don't'."},
      ],
    },
    {
      "code": "polite",
      "l1_title": "Politeness",
      "tags": [
        {"code": "Infm", "l1_title": "Informal", "l1_description": "A casual form used with friends or family."},
        {"code": "Form", "l1_title": "Formal", "l1_description": "A polite form used to show respect."},
        {"code": "Elev", "l1_title": "Elevated", "l1_description": "An especially respectful form for the listener."},
        {"code": "Humb", "l1_title": "Humble", "l1_description": "A form humbling the speaker in deference."},
      ],
    },
    {
      "code": "poss",
      "l1_title": "Possessive",
      "tags": [
        {"code": "Yes", "l1_title": "Possessive", "l1_description": "Indicates ownership, like 'my' or 'their'."},
      ],
    },
    {
      "code": "prepcase",
      "l1_title": "Prepositional case",
      "tags": [
        {"code": "Npr", "l1_title": "Non-prepositional", "l1_description": "A form not used with a preposition."},
      ],
    },
    {
      "code": "prontype",
      "l1_title": "Pronoun type",
      "tags": [
        {"code": "Prs", "l1_title": "Personal", "l1_description": "Refers to a person, like 'I' or 'she'."},
        {"code": "Int", "l1_title": "Interrogative", "l1_description": "Asks a question, like 'who' or 'what'."},
        {"code": "Rel", "l1_title": "Relative", "l1_description": "Introduces a relative clause, like 'who' or 'that'."},
        {"code": "Dem", "l1_title": "Demonstrative", "l1_description": "Points to something, like 'this' or 'that'."},
        {"code": "Tot", "l1_title": "Total", "l1_description": "Refers to everyone or everything, like 'all' or 'every'."},
        {"code": "Neg", "l1_title": "Negative", "l1_description": "Refers to no one or nothing, like 'nobody' or 'nothing'."},
        {"code": "Art", "l1_title": "Article", "l1_description": "Functions like 'a' or 'the' in some languages."},
        {"code": "Emp", "l1_title": "Emphatic", "l1_description": "Adds emphasis, like 'himself' or 'myself'."},
        {"code": "Exc", "l1_title": "Exclamative", "l1_description": "Used in exclamations, like 'what a day!'"},
        {"code": "Ind", "l1_title": "Indefinite", "l1_description": "Refers to something unspecified, like 'someone' or 'anything'."},
        {"code": "Rcp", "l1_title": "Reciprocal", "l1_description": "Refers to each other, like 'each other'."},
        {"code": "Int,Rel", "l1_title": "Interrogative/Relative", "l1_description": "A pronoun that can be either question or relative, like 'who'."},
      ],
    },
    {
      "code": "punctside",
      "l1_title": "Punctuation side",
      "tags": [
        {"code": "Ini", "l1_title": "Initial", "l1_description": "An opening punctuation mark, like '(' or '['."},
        {"code": "Fin", "l1_title": "Final", "l1_description": "A closing punctuation mark, like ')' or ']'."},
      ],
    },
    {
      "code": "puncttype",
      "l1_title": "Punctuation type",
      "tags": [
        {"code": "Brck", "l1_title": "Bracket", "l1_description": "A bracket-like mark, such as '(' or '['."},
        {"code": "Dash", "l1_title": "Dash", "l1_description": "A dash or hyphen, like '-' or '—'."},
        {"code": "Excl", "l1_title": "Exclamation", "l1_description": "An exclamation mark, '!'."},
        {"code": "Peri", "l1_title": "Period", "l1_description": "A period or full stop, '.'."},
        {"code": "Qest", "l1_title": "Question", "l1_description": "A question mark, '?'."},
        {"code": "Quot", "l1_title": "Quotation", "l1_description": "A quotation mark, like '\"'."},
        {"code": "Semi", "l1_title": "Semicolon", "l1_description": "A semicolon, ';'."},
        {"code": "Colo", "l1_title": "Colon", "l1_description": "A colon, ':'."},
        {"code": "Comm", "l1_title": "Comma", "l1_description": "A comma, ','."},
      ],
    },
    {
      "code": "reflex",
      "l1_title": "Reflexive",
      "tags": [
        {"code": "Yes", "l1_title": "Reflexive", "l1_description": "Refers back to the subject, like 'myself' or 'herself'."},
      ],
    },
    {
      "code": "tense",
      "l1_title": "Tense",
      "tags": [
        {"code": "Pres", "l1_title": "Present", "l1_description": "Something happening now, like 'walks'."},
        {"code": "Past", "l1_title": "Past", "l1_description": "Something that already happened, like 'walked'."},
        {"code": "Fut", "l1_title": "Future", "l1_description": "Something that will happen, like 'will walk'."},
        {"code": "Imp", "l1_title": "Imperfect", "l1_description": "An ongoing or habitual past action, like 'was walking'."},
        {"code": "Pqp", "l1_title": "Pluperfect", "l1_description": "An action completed before another past action, like 'had walked'."},
        {"code": "Aor", "l1_title": "Aorist", "l1_description": "A simple past action viewed as a whole, common in Greek and Slavic."},
        {"code": "Eps", "l1_title": "Episodic past", "l1_description": "A specific past episode, used in some languages."},
        {"code": "Prosp", "l1_title": "Prospective", "l1_description": "An action about to happen, like 'is going to walk'."},
      ],
    },
    {
      "code": "verbform",
      "l1_title": "Verb form",
      "tags": [
        {"code": "Fin", "l1_title": "Finite", "l1_description": "A conjugated verb that agrees with its subject, like 'runs'."},
        {"code": "Inf", "l1_title": "Infinitive", "l1_description": "The base form of a verb, like 'to run'."},
        {"code": "Sup", "l1_title": "Supine", "l1_description": "A verb form used for purpose, common in Latin and Swedish."},
        {"code": "Part", "l1_title": "Participle", "l1_description": "A verb form used as an adjective, like 'running' or 'broken'."},
        {"code": "Conv", "l1_title": "Converb", "l1_description": "A non-finite verb form that links clauses adverbially."},
        {"code": "Vnoun", "l1_title": "Verbal noun", "l1_description": "A noun form derived from a verb, like 'running' as a noun."},
        {"code": "Ger", "l1_title": "Gerund", "l1_description": "An '-ing' verb form used as a noun, like 'running is fun'."},
        {"code": "Adn", "l1_title": "Adnominal", "l1_description": "A verb form modifying a noun, like Korean adnominal endings."},
        {"code": "Lng", "l1_title": "Long form", "l1_description": "A longer or fuller form of a verb, used in some languages."},
      ],
    },
    {
      "code": "verbtype",
      "l1_title": "Verb type",
      "tags": [
        {"code": "Mod", "l1_title": "Modal", "l1_description": "Expresses possibility, necessity, or permission, like 'can' or 'must'."},
        {"code": "Caus", "l1_title": "Causative", "l1_description": "Indicates causing an action, like 'make someone do' something."},
      ],
    },
    {
      "code": "voice",
      "l1_title": "Voice",
      "tags": [
        {"code": "Act", "l1_title": "Active", "l1_description": "The subject does the action, like 'she wrote a book'."},
        {"code": "Mid", "l1_title": "Middle", "l1_description": "The subject acts on or for itself, between active and passive."},
        {"code": "Pass", "l1_title": "Passive", "l1_description": "The subject receives the action, like 'the book was written'."},
        {"code": "Antip", "l1_title": "Antipassive", "l1_description": "In ergative languages, demotes the object so the agent surfaces as subject."},
        {"code": "Cau", "l1_title": "Causative", "l1_description": "Marks a verb whose subject causes the action."},
        {"code": "Dir", "l1_title": "Direct", "l1_description": "A direct voice form, used in some inverse-marking systems."},
        {"code": "Inv", "l1_title": "Inverse", "l1_description": "An inverse voice form, used in some inverse-marking systems."},
        {"code": "Rcp", "l1_title": "Reciprocal", "l1_description": "The participants act on each other, like 'they hugged each other'."},
        {"code": "Caus", "l1_title": "Causative", "l1_description": "Indicates causing an action, like 'made him run'."},
      ],
    },
    {
      "code": "x",
      "l1_title": "Other",
      "tags": [
        {"code": "X", "l1_title": "Other", "l1_description": "A value that doesn't fit a standard category."},
      ],
    },
  ],
});
