import 'dart:convert';
import 'dart:io';

import 'package:matrix/matrix.dart';

import 'package:fluffychat/features/analytics/analytics_constants.dart';
import 'package:fluffychat/features/analytics/construct_identifier.dart';
import 'package:fluffychat/features/analytics/construct_level_enum.dart';
import 'package:fluffychat/features/analytics/construct_type_enum.dart';
import 'package:fluffychat/features/analytics/construct_use_model.dart';
import 'package:fluffychat/features/analytics/construct_use_type_enum.dart';
import 'package:fluffychat/features/analytics/constructs_event.dart';
import 'package:fluffychat/features/analytics/constructs_model.dart';
import 'package:fluffychat/features/analytics/saved_analytics_extension.dart';
import 'package:fluffychat/features/analytics_data/analytics_data_service.dart';
import 'package:fluffychat/features/analytics_data/analytics_settings_extension.dart';
import 'package:fluffychat/features/analytics_data/construct_merge_table.dart';
import 'package:fluffychat/features/analytics_data/derived_analytics_data_model.dart';
import 'package:fluffychat/routes/chat/chat_details/space_analytics/space_analytics_summary_model.dart';
import 'package:fluffychat/routes/chat/events/constants/pangea_event_types.dart';
import '../get_test_client.dart';

/// Analytics parity goldens: the app's own analytics formulas, run over a
/// fixed set of analytics-room inputs, recorded as JSON for other services
/// (admin-dash-api) to check their ports against.
///
/// Test-only. Nothing here re-implements a formula: every figure comes from
/// the app code in lib/ called as-is, with one exception noted at
/// [_learnerAggregate]. Paths are relative to the package root, which is the
/// working directory `flutter test` runs in.
const fixturesPath =
    'test/pangea/analytics_parity/fixtures/analytics_cases.json';
const goldensPath = 'test/pangea/analytics_parity/goldens.json';
const regenerateCommand =
    'flutter test --dart-define=UPDATE_ANALYTICS_GOLDENS=true '
    'test/pangea/analytics_parity/generate_goldens_test.dart';

/// Bump when the goldens' SHAPE changes (keys added, renamed or removed), so a
/// consumer can refuse a file it does not understand. A formula change alone
/// changes values, not the schema.
const goldensSchemaVersion = 1;

/// The lib/ files whose formulas the goldens exercise. A change to any of
/// these should be followed by a regeneration; CI runs the check on them.
const formulaSources = [
  'lib/features/analytics/construct_identifier.dart',
  'lib/features/analytics/construct_use_model.dart',
  'lib/features/analytics/construct_use_type_enum.dart',
  'lib/features/analytics/constructs_model.dart',
  'lib/features/analytics/analytics_constants.dart',
  'lib/features/analytics/saved_analytics_extension.dart',
  'lib/features/analytics_data/analytics_data_service.dart',
  'lib/features/analytics_data/analytics_settings_model.dart',
  'lib/features/analytics_data/construct_merge_table.dart',
  'lib/features/analytics_data/derived_analytics_data_model.dart',
  'lib/pangea/morphs/morph_features_enum.dart',
  'lib/routes/chat/chat_details/space_analytics/space_analytics_summary_model.dart',
];

/// Fixed origin for every timestamp the generator assigns, so output never
/// depends on the clock.
final _t0 = DateTime.utc(2026, 1, 1);

/// XP totals the level curve is sampled at: the formula's edges (the NaN
/// region below -37.5 XP maps to level 1), level boundaries and large totals.
const _levelCurveXp = [
  -100, -38, -37, 0, 1, 37, 38, 112, 113, 262, 263, 299, 300, 675, 676, //
  900, 1500, 5000, 10000, 100000,
];

/// Builds the full goldens document from [fixturesPath].
Future<Map<String, dynamic>> buildAnalyticsGoldens() async {
  final fixtureFile = File(fixturesPath);
  if (!fixtureFile.existsSync()) {
    throw StateError(
      '$fixturesPath not found from ${Directory.current.path}. '
      'Run flutter test from the client package root.',
    );
  }
  final fixtures = jsonDecode(fixtureFile.readAsStringSync()) as Map;
  final cases = (fixtures['cases'] as List).cast<Map<String, dynamic>>();

  final client = await getTestClient(name: 'analytics_goldens');
  try {
    final names = <String>{};
    final outCases = <Map<String, dynamic>>[];
    for (final c in cases) {
      final name = c['name'] as String;
      if (!names.add(name)) throw StateError('duplicate case name $name');
      outCases.add(_runCase(client, c));
    }
    return _canonical({
          'schema_version': goldensSchemaVersion,
          'about':
              'Generated by the client analytics parity generator from '
              '$fixturesPath. Do not edit by hand; regenerate with: '
              '$regenerateCommand',
          'formula_sources': formulaSources,
          'constants': {
            'xpForGreens': AnalyticsConstants.xpForGreens,
            'xpForFlower': AnalyticsConstants.xpForFlower,
            'levelCurveD': DerivedAnalyticsDataModel.D,
          },
          'use_types': [
            for (final t in ConstructUseTypeEnum.values)
              {
                'name': t.name,
                'pointValue': t.pointValue,
                'sentByUser': t.sentByUser,
                'summaryEnumType': t.summaryEnumType?.name,
              },
          ],
          'level_curve': {
            'xpToLevel': [
              for (final xp in _levelCurveXp)
                {
                  'xp': xp,
                  'level': DerivedAnalyticsDataModel.calculateLevelWithXp(xp),
                },
            ],
            'levelToMinXp': [
              for (var level = 0; level <= 30; level++)
                {
                  'level': level,
                  'minXp': DerivedAnalyticsDataModel.calculateXpWithLevel(
                    level,
                  ),
                },
            ],
          },
          'cases': outCases,
        })
        as Map<String, dynamic>;
  } finally {
    await client.dispose(closeDatabase: true);
  }
}

/// The goldens document as the exact bytes written to [goldensPath].
String encodeGoldens(Map<String, dynamic> goldens) =>
    '${const JsonEncoder.withIndent('  ').convert(goldens)}\n';

Map<String, dynamic> _runCase(Client client, Map<String, dynamic> c) {
  final name = c['name'] as String;
  final xpOffset = c['xp_offset'] as int? ?? 0;
  final blockedJson = (c['blocked_constructs'] as List? ?? const [])
      .cast<Map<String, dynamic>>();
  final activityRoomIds = (c['activity_room_ids'] as List? ?? const [])
      .cast<String>();

  // Expand the fixture conventions into the exact event content the app
  // reads, so goldens.json carries inputs that need no further interpretation.
  var useIndex = 0;
  final events = <Map<String, dynamic>>[];
  for (final e in (c['events'] as List).cast<Map<String, dynamic>>()) {
    final uses = <Map<String, dynamic>>[];
    for (final raw in (e['uses'] as List).cast<Map<String, dynamic>>()) {
      final repeat = raw['_repeat'] as int? ?? 1;
      for (var i = 0; i < repeat; i++) {
        final use = Map<String, dynamic>.from(raw)..remove('_repeat');
        use['timeStamp'] ??= _t0
            .add(Duration(minutes: useIndex))
            .toIso8601String();
        useIndex++;
        uses.add(use);
      }
    }
    events.add({
      'event_id': '\$${name}_${events.length}',
      'origin_server_ts': _t0
          .add(Duration(hours: events.length))
          .toIso8601String(),
      'content': {'uses': uses},
    });
  }

  // The learner's analytics room, with the two state events the teacher view
  // reads through the app's own room extensions.
  final room = Room(id: '!$name:example.org', client: client);
  room.setState(
    Event(
      type: PangeaEventTypes.analyticsSettings,
      stateKey: '',
      content: {'blocked_constructs': blockedJson},
      eventId: '\$${name}_settings',
      senderId: client.userID!,
      originServerTs: _t0,
      room: room,
    ),
  );
  room.setState(
    Event(
      type: PangeaEventTypes.activityRoomIds,
      stateKey: '',
      content: {AnalyticsConstants.roomIds: activityRoomIds},
      eventId: '\$${name}_activities',
      senderId: client.userID!,
      originServerTs: _t0,
      room: room,
    ),
  );
  final blocked = room.blockedConstructs;

  // Deep copies: the app parses the content, and nothing it does may be able
  // to reach back into the inputs recorded in the goldens.
  final constructEvents = [
    for (final e in events)
      ConstructAnalyticsEvent(
        event: Event(
          content: jsonDecode(jsonEncode(e['content'])),
          type: PangeaEventTypes.construct,
          eventId: e['event_id'] as String,
          senderId: client.userID!,
          originServerTs: DateTime.parse(e['origin_server_ts'] as String),
          room: room,
          status: EventStatus.synced,
        ),
      ),
  ];

  final summary = SpaceAnalyticsSummaryModel.fromEvents(
    '@learner:example.org',
    constructEvents,
    blocked,
    room.archivedActivitiesCount,
  );

  return {
    'name': name,
    'description': c['description'],
    'input': {
      'xp_offset': xpOffset,
      'blocked_constructs': blockedJson,
      'activity_room_ids': activityRoomIds,
      'events': events,
    },
    'teacher': _teacherSummary(summary),
    'learner': _learnerAggregate(constructEvents, blocked, xpOffset),
  };
}

/// Every figure of the teacher-side space analytics summary
/// ([SpaceAnalyticsSummaryModel.fromEvents]), under its Dart field name.
/// String lists are sorted: they are sets of lemmas whose order is the
/// summary's internal map order, not something a consumer should match.
Map<String, dynamic> _teacherSummary(SpaceAnalyticsSummaryModel s) {
  List<String>? sorted(List<String>? l) => l == null ? null : ([...l]..sort());
  return {
    'dataAvailable': s.dataAvailable,
    'level': s.level,
    'totalXP': s.totalXP,
    'numLemmas': s.numLemmas,
    'numLemmasUsedCorrectly': s.numLemmasUsedCorrectly,
    'numLemmasUsedIncorrectly': s.numLemmasUsedIncorrectly,
    'numLemmasSmallXP': s.numLemmasSmallXP,
    'numLemmasMediumXP': s.numLemmasMediumXP,
    'numLemmasLargeXP': s.numLemmasLargeXP,
    'numMorphConstructs': s.numMorphConstructs,
    'listMorphConstructs': sorted(s.listMorphConstructs),
    'listMorphConstructsUsedCorrectlyOriginal': sorted(
      s.listMorphConstructsUsedCorrectlyOriginal,
    ),
    'listMorphConstructsUsedIncorrectlyOriginal': sorted(
      s.listMorphConstructsUsedIncorrectlyOriginal,
    ),
    'listMorphConstructsUsedCorrectlySystem': sorted(
      s.listMorphConstructsUsedCorrectlySystem,
    ),
    'listMorphConstructsUsedIncorrectlySystem': sorted(
      s.listMorphConstructsUsedIncorrectlySystem,
    ),
    'listMorphSmallXP': sorted(s.listMorphSmallXP),
    'listMorphMediumXP': sorted(s.listMorphMediumXP),
    'listMorphLargeXP': sorted(s.listMorphLargeXP),
    'listMorphHugeXP': sorted(s.listMorphHugeXP),
    'numMessagesSent': s.numMessagesSent,
    'numWordsTyped': s.numWordsTyped,
    'numChoicesCorrect': s.numChoicesCorrect,
    'numChoicesIncorrect': s.numChoicesIncorrect,
    'numCompletedActivities': s.numCompletedActivities,
  };
}

/// The learner-side figures for the same room: what the learner's own
/// analytics show.
///
/// The local store keeps one aggregate row per construct identifier; those
/// rows are rebuilt here from the parsed uses. Total XP is
/// [AnalyticsDataService.foldTotalXP], counts are
/// [ConstructMergeTable.uniqueConstructsByType], level is
/// [DerivedAnalyticsDataModel] over the total plus the XP offset.
///
/// The one exception to "no re-implementation": the tier counts need the
/// canonical constructs `AnalyticsDataService.getAggregatedConstructs` builds,
/// and that method needs the full service and its database. Its resolve /
/// merge / drop-blocked-or-invalid loop is mirrored below line for line; the
/// tier itself is [ConstructUses.lemmaCategory].
Map<String, dynamic> _learnerAggregate(
  List<ConstructAnalyticsEvent> events,
  Set<ConstructIdentifier> blocked,
  int xpOffset,
) {
  // Insertion-ordered, like the store's rows: order decides merge-table
  // canonicals, so it must not depend on hashing.
  final usesById = <ConstructIdentifier, List<OneConstructUse>>{};
  for (final e in events) {
    for (final use in e.content.uses) {
      (usesById[use.identifier] ??= []).add(use);
    }
  }

  ConstructUses row(ConstructIdentifier id) => ConstructUses(
    uses: usesById[id]!,
    constructType: id.type,
    lemma: id.lemma,
    category: id.category,
  );

  final mergeTable = ConstructMergeTable()
    ..addIdentifiers(usesById.keys, blocked);

  final rawTotalXP = AnalyticsDataService.foldTotalXP(
    [
      for (final id in usesById.keys)
        (id: id, xp: row(id).uses.fold<int>(0, (t, u) => t + u.xp)),
    ],
    resolve: mergeTable.resolve,
    blocked: blocked,
  );
  final derived = DerivedAnalyticsDataModel(
    totalXP: rawTotalXP,
    offset: xpOffset,
  );

  // Mirror of AnalyticsDataService.getAggregatedConstructs (see doc above).
  final cleaned = <ConstructIdentifier, ConstructUses>{};
  for (final entry in usesById.keys.map(row)) {
    final canonical = mergeTable.resolve(entry.id);
    final existing = cleaned[canonical];
    if (existing != null) {
      existing.merge(entry);
    } else if (!blocked.contains(canonical) && !canonical.isInvalid) {
      cleaned[canonical] = entry;
    }
  }

  Map<String, int> tiers(ConstructTypeEnum type) => {
    for (final level in ConstructLevelEnum.values)
      level.name: cleaned.values
          .where((c) => c.constructType == type && c.lemmaCategory == level)
          .length,
  };

  final constructs =
      [
        for (final entry in cleaned.entries)
          {
            'lemma': entry.key.lemma,
            'type': entry.key.type.string,
            'category': entry.key.category,
            'points': entry.value.points,
            'tier': entry.value.lemmaCategory.name,
          },
      ]..sort(
        (a, b) => '${a['type']}|${a['lemma']}|${a['category']}'.compareTo(
          '${b['type']}|${b['lemma']}|${b['category']}',
        ),
      );

  return {
    'rawTotalXP': rawTotalXP,
    'xpOffset': derived.offset,
    'totalXP': derived.totalXP,
    'level': derived.level,
    'levelProgress': derived.levelProgress,
    'minXPForNextLevel': derived.minXPForNextLevel,
    'vocabCount': mergeTable.uniqueConstructsByType(ConstructTypeEnum.vocab),
    'grammarCount': mergeTable.uniqueConstructsByType(ConstructTypeEnum.morph),
    'vocabTiers': tiers(ConstructTypeEnum.vocab),
    'grammarTiers': tiers(ConstructTypeEnum.morph),
    'constructs': constructs,
  };
}

/// [value] with every map's keys in sorted order, so the encoded document is
/// byte-stable regardless of how it was assembled.
Object? _canonical(Object? value) {
  if (value is Map) {
    final keys = value.keys.map((k) => k as String).toList()..sort();
    return <String, dynamic>{for (final k in keys) k: _canonical(value[k])};
  }
  if (value is List) return [for (final v in value) _canonical(v)];
  return value;
}

/// Paths (JSON-pointer style) at which [a] and [b] differ, each with both
/// values, for a failure message a reviewer can act on.
List<String> diffGoldens(Object? a, Object? b, [String path = '']) {
  if (a is Map && b is Map) {
    final keys = {...a.keys, ...b.keys}.map((k) => k as String).toList()
      ..sort();
    return [
      for (final k in keys)
        if (!a.containsKey(k))
          '$path/$k: added ${jsonEncode(b[k])}'
        else if (!b.containsKey(k))
          '$path/$k: removed (was ${jsonEncode(a[k])})'
        else
          ...diffGoldens(a[k], b[k], '$path/$k'),
    ];
  }
  if (a is List && b is List) {
    if (a.length != b.length) {
      return [
        '$path: length ${a.length} -> ${b.length} '
            '(${jsonEncode(a)} -> ${jsonEncode(b)})',
      ];
    }
    return [
      for (var i = 0; i < a.length; i++) ...diffGoldens(a[i], b[i], '$path/$i'),
    ];
  }
  if (a != b) return ['$path: ${jsonEncode(a)} -> ${jsonEncode(b)}'];
  return const [];
}
