linter:
  rules:
    - camel_case_types
    - avoid_print
    - constant_identifier_names
    - prefer_final_locals
    - prefer_final_in_for_each
    - prefer_relative_imports
    - unawaited_futures
    - require_trailing_commas

analyzer:
  errors:
    todo: ignore
    fixme: ignore
