name: fcm_shared_isolate
description: Firebase Messaging Plugin for Flutter supporting shared isolate
homepage: https://famedly.com
version: 0.2.0
repository: https://github.com/famedly/fcm_shared_isolate
issue_tracker: https://github.com/famedly/fcm_shared_isolate/issues

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ">=2.0.0 <4.0.0"
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.famedly.fcm_shared_isolate
        pluginClass: FcmSharedIsolatePlugin
      ios:
        pluginClass: FcmSharedIsolatePlugin
