name: Main Deploy Workflow

on:
  push:
    branches:
      - gh-action-android-ios
  workflow_dispatch:

env:
  WEB_APP_ENV: ${{ vars.WEB_APP_ENV }}
  
jobs:
  # switch-branch:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout main branch
  #     uses: actions/checkout@v3

  #   - name: Checkout different branch
  #     run: git checkout development


  deploy_ios_internal:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat .github/workflows/versions.env >> $GITHUB_ENV
      - run: 'echo "$API_KEY" | base64 --decode > AuthKey.p8'
        shell: bash
        env:
          API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Use local my-action
        uses: ./.github/workflows/build-ios.yml
      - name: Use local my-action
        uses: ./.github/workflows/upload-release-ios.yml