name: Main Deploy Workflow

on:
  push:
    branches:
      - gh-action-android-ios
  workflow_dispatch:

env:
  WEB_APP_ENV: ${{ vars.WEB_APP_ENV }}
  
jobs:
  # switch-branch:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout main branch
  #     uses: actions/checkout@v3

  #   - name: Checkout different branch
  #     run: git checkout development


  deploy_ios_internal:
    runs-on: macos-latest
    environment: staging
    defaults:
      run:
        working-directory: ./ios
    steps:
      - uses: actions/checkout@v4
      - run: cat ../.github/workflows/versions.env >> $GITHUB_ENV
      - run: 'echo "$API_KEY" | base64 --decode > AuthKey.p8'
        shell: bash
        env:
          API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}

      - run: bundle install

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
      - run: flutter build ios --simulator --target=integration_test/screenshot_test.dart
        if: ${{ inputs.screenshot == 'true' }}

      - name: Archive integration ipa
        if: ${{ inputs.screenshot == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: app-simulator-build
          path: build/ios/iphonesimulator/Runner.app
          if-no-files-found: error
          retention-days: 3

      # Build ios Release
      - run: flutter build ios --release --config-only --no-codesign --target=lib/main.dart

      - run: 'echo "$API_KEY_JSON" | base64 --decode > api_key_info.json'
        shell: bash
        env:
          API_KEY_JSON: ${{ secrets.APP_STORE_CONNECT_API_KEY_JSON }}

      - run: bundle exec fastlane upload_testflight --api_key_path api_key_info.json

      - run: bundle exec fastlane upload_metadata_app_store