name: Main Deploy Workflow

on:
  push:
    branches:
      - main
      - gh-actions-improvements

env:
  # Setting an environment variable with the value of a configuration variable
  WEB_APP_ENV: ${{ vars.WEB_APP_ENV }}
  
jobs:
  deploy_web:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - run: cat .github/workflows/versions.env >> $GITHUB_ENV
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install nodejs -y
      - run: flutter pub get
      - name: Prepare web
        run: ./scripts/prepare-web.sh
      - name: Build Release Web
        run: ./scripts/build-web.sh
      - name: Build Website
        run: |
          mv build/web public
          touch public/.env
          echo "$WEB_APP_ENV" >> public/.env
          cp public/.env public/assets/.env
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          cname: app.staging.pangea.chat
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: public

  update_sentry:
    runs-on: ubuntu-latest
    needs: deploy_web
    steps:
      - uses: actions/checkout@v2
      - uses: getsentry/sentry-cli
      - name: Download web
        uses: actions/download-artifact@v3
        with:
          name: web
      - name: Move files to orignal
        run: |
          mv public build/web
      - name: Update sentry
        run: ./scripts/build-web.sh
