name: Old Release Workflow

on:
  push:
    branches:
      - master-unused

concurrency:
  group: release_workflow
  cancel-in-progress: true

jobs:
  deploy_ios_internal:
    runs-on: macos-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - run: cat ../.github/workflows/versions.env >> $GITHUB_ENV

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"

      # Build ios Release
      - run: flutter build ios --release --config-only --no-codesign --target=lib/main.dart

      - name: Deploy ios
        run: |
          mkdir -p build/ios
          cp build/app/outputs/bundle/release/app-release.aab build/ios/
          cd ios
          bundle install
          bundle update fastlane
          cd ..
      - name: Execute fastlane signing
        env:
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: ${{ secrets.APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64 }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
        run: bundle exec fastlane ios beta